import { useState, useCallback } from 'react';
import { toast } from 'sonner';
import { useTournamentDb } from '@/hooks/useTournamentDb';
import { useAuth } from '@/hooks/useAuth';
import { useClubs } from '@/hooks/useClubs';
import { useClubPlayers } from '@/hooks/useClubPlayers';
import { TournamentSelector } from '@/components/TournamentSelector';
import { TournamentMediaTab } from '@/components/TournamentMediaTab';
import { PlayerManager } from '@/components/PlayerManager';
import { PlayerImportExport } from '@/components/PlayerImportExport';
import { ImportFromClubPlayers } from '@/components/ImportFromClubPlayers';
import { ClubManager } from '@/components/ClubManager';
import { ClubPlayersManager } from '@/components/ClubPlayersManager';
import { TournamentBracket } from '@/components/TournamentBracket';
import { MatchScoring } from '@/components/MatchScoring';
import { LiveDashboard } from '@/components/LiveDashboard';
import { EncounterView } from '@/components/EncounterView';
import { TournamentOverview } from '@/components/TournamentOverview';
import { LogoUpload } from '@/components/LogoUpload';
import { DoublesManager } from '@/components/DoublesManager';
import { RoundRobinStandings } from '@/components/RoundRobinStandings';
import { DoubleEliminationBracket } from '@/components/DoubleEliminationBracket';
import { SwissStandings } from '@/components/SwissStandings';
import { GroupStageView } from '@/components/GroupStageView';
import { generateGroupStageReport } from '@/components/GroupStageReport';
import { TournamentSettingsDialog } from '@/components/TournamentSettingsDialog';
import { TeamManager } from '@/components/TeamManager';
import { TeamEncounterScoring } from '@/components/TeamEncounterScoring';
import { KaiserScoring } from '@/components/KaiserScoring';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Users, Swords, PenLine, Monitor, RotateCcw, Play, ArrowLeft, Loader2, ClipboardList, LogOut, Building2, Users2, Pencil, FileDown, Shield, Settings, Film, Video } from 'lucide-react';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { GlobalSettings } from '@/components/GlobalSettings';
import { Input } from '@/components/ui/input';
import { PageTransition, FadeIn } from '@/components/ui/motion';

const Index = () => {
  const { signOut } = useAuth();
  const { clubs, addClub, removeClub, updateClub } = useClubs();
  const { players: clubPlayers, addPlayer: addClubPlayer, updatePlayer: updateClubPlayer, removePlayer: removeClubPlayer, getPlayersForClub } = useClubPlayers();
  const [selectedTournamentId, setSelectedTournamentId] = useState<string | null>(null);
  const {
    tournament,
    loading,
    addPlayer,
    removePlayer,
    updatePlayer,
    importPlayers,
    generateBracket,
    updateMatchScore,
    setMatchActive,
    getPlayer,
    setTableCount,
    autoAssignTables,
    updateLogoUrl,
    updateName,
    updateTournamentMode,
    updateTournamentType,
    updateBestOf,
    addDoublesPair,
    removeDoublesPair,
    autoGenerateDoublesPairs,
    getParticipantName,
    updateDetails,
    advanceToKnockout,
    resetTournament,
    generateNextSwissRound,
    addTeam,
    removeTeam,
    addPlayerToTeam,
    removePlayerFromTeam,
    updateTeamMode,
    updateEarlyFinish,
    encounterGames,
    loadEncounterGames,
    updateEncounterGameScore,
    updateKaiserDuration,
    generateNextKaiserRound,
  } = useTournamentDb(selectedTournamentId);

  const [tab, setTab] = useState('players');
  const [homeTab, setHomeTab] = useState<'tournaments' | 'clubs' | 'settings'>('tournaments');
  const [editingName, setEditingName] = useState(false);
  const [nameValue, setNameValue] = useState('');

  const isDoubles = tournament.type === 'doubles';
  const isTeam = tournament.type === 'team';
  const isRoundRobin = tournament.mode === 'round_robin';
  const isGroupKnockout = tournament.mode === 'group_knockout';
  const isDoubleKnockout = tournament.mode === 'double_knockout';
  const isSwiss = tournament.mode === 'swiss';
  const isKaiser = tournament.mode === 'kaiser';
  const isHandicap = tournament.mode === 'handicap';
  const venueString = [tournament.venueStreet, tournament.venueHouseNumber, tournament.venuePostalCode, tournament.venueCity].filter(Boolean).join(' ') || undefined;
  const [openingVideoPlayerOpen, setOpeningVideoPlayerOpen] = useState(false);

  const handleImportClubsWithPlayers = useCallback(async (data: Array<{ clubName: string; players: Array<{ name: string; club: string; ttr: number; gender: string; birthDate: string | null; postalCode: string; city: string; street: string; houseNumber: string; phone: string }> }>) => {
    for (const entry of data) {
      const existing = clubs.find(c => c.name === entry.clubName);
      if (!existing) {
        await addClub(entry.clubName);
      }
      if (entry.players.length > 0 && selectedTournamentId) {
        for (const p of entry.players) {
          await addPlayer(p.name, p.club, p.ttr, p.gender, p.birthDate, p.postalCode, p.city, p.street, p.houseNumber, p.phone);
        }
      }
    }
  }, [clubs, addClub, addPlayer, selectedTournamentId]);

  // Can start?
  const minPlayers = isDoubleKnockout ? 3 : 2;
  const canStart = !tournament.started && (
    isTeam
      ? tournament.teams.length >= 2
      : isDoubles
        ? tournament.doublesPairs.length >= minPlayers
        : tournament.players.length >= minPlayers
  );

  // If no tournament selected, show tournament list
  if (!selectedTournamentId) {
    return (
      <div className="min-h-screen bg-background">
        <header className="glass border-b border-border/50 sticky top-0 z-50">
          <div className="container py-4 flex items-center gap-3">
            <span className="text-2xl">🏓</span>
            <div className="flex-1 min-w-0">
              <h1 className="text-sm sm:text-lg font-bold tracking-tight leading-tight font-display">
                <span className="text-gradient">TT</span> Turniermanager
                <span className="hidden sm:inline text-foreground/80"> SV Straßgräbchen</span>
              </h1>
              <span className="text-[11px] text-muted-foreground hidden sm:block">Sektion Tischtennis</span>
            </div>
            <Button variant="ghost" size="icon" onClick={signOut} className="h-8 w-8 text-muted-foreground hover:text-foreground">
              <LogOut className="h-4 w-4" />
            </Button>
          </div>
        </header>
        <PageTransition className="container py-8">
          <FadeIn delay={0.1}>
          <div className="flex gap-1 mb-6 bg-secondary/50 p-1 rounded-xl w-fit">
            <Button
              variant={homeTab === 'tournaments' ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setHomeTab('tournaments')}
              className={`gap-1.5 rounded-lg text-xs font-medium ${homeTab !== 'tournaments' ? 'text-muted-foreground hover:text-foreground' : ''}`}
            >
              <Swords className="h-3.5 w-3.5" />
              Turniere
            </Button>
            <Button
              variant={homeTab === 'clubs' ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setHomeTab('clubs')}
              className={`gap-1.5 rounded-lg text-xs font-medium ${homeTab !== 'clubs' ? 'text-muted-foreground hover:text-foreground' : ''}`}
            >
              <Building2 className="h-3.5 w-3.5" />
              Vereine
            </Button>
            <Button
              variant={homeTab === 'settings' ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setHomeTab('settings')}
              className={`gap-1.5 rounded-lg text-xs font-medium ${homeTab !== 'settings' ? 'text-muted-foreground hover:text-foreground' : ''}`}
            >
              <Settings className="h-3.5 w-3.5" />
              Einstellungen
            </Button>
          </div>
          </FadeIn>
          {homeTab === 'tournaments' ? (
            <TournamentSelector
              selectedId={selectedTournamentId}
              onSelect={(id) => setSelectedTournamentId(id || null)}
            />
          ) : homeTab === 'clubs' ? (
            <ClubPlayersManager
              clubs={clubs}
              clubPlayers={clubPlayers}
              onAddClub={addClub}
              onRemoveClub={removeClub}
              onUpdateClub={updateClub}
              onAddPlayer={addClubPlayer}
              onUpdatePlayer={updateClubPlayer}
              onRemovePlayer={removeClubPlayer}
              getPlayersForClub={getPlayersForClub}
            />
          ) : (
            <GlobalSettings />
          )}
        </PageTransition>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  const modeLabel = isRoundRobin ? 'Jeder gg. Jeden' : isGroupKnockout ? 'Gruppen+KO' : isDoubleKnockout ? 'Doppel-KO' : isSwiss ? 'Schweizer' : isKaiser ? 'Kaiser' : isHandicap ? 'Vorgabe' : 'KO';
  const typeLabel = isTeam ? 'Mannschaft' : isDoubles ? 'Doppel' : 'Einzel';

  const tabCount = isTeam ? 8 : isDoubles ? 8 : 7;

  return (
    <PageTransition className="min-h-screen bg-background">
      {/* Header */}
      <header className="glass border-b border-border/50 sticky top-0 z-50">
        <div className="container py-3 flex items-center justify-between">
          <div className="flex items-center gap-2 min-w-0">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setSelectedTournamentId(null)}
              className="h-8 w-8 flex-shrink-0 text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="h-4 w-4" />
            </Button>
            <LogoUpload
              tournamentId={selectedTournamentId}
              logoUrl={tournament.logoUrl}
              onLogoChange={updateLogoUrl}
            />
            <div className="min-w-0">
              {editingName ? (
                <Input
                  autoFocus
                  value={nameValue}
                  onChange={e => setNameValue(e.target.value)}
                  onBlur={() => { updateName(nameValue); setEditingName(false); }}
                  onKeyDown={e => { if (e.key === 'Enter') { updateName(nameValue); setEditingName(false); } if (e.key === 'Escape') setEditingName(false); }}
                  className="h-7 text-sm sm:text-lg font-bold w-48 sm:w-64 font-display"
                />
              ) : (
                <div className="flex items-center gap-1 group cursor-pointer" onClick={() => { setNameValue(tournament.name); setEditingName(true); }}>
                  <h1 className="text-sm sm:text-lg font-bold tracking-tight leading-tight truncate font-display">
                    {tournament.name || 'Turnier'}
                  </h1>
                  <Pencil className="h-3 w-3 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0" />
                </div>
              )}
              <div className="flex gap-1.5 mt-0.5">
                <span className="text-[10px] bg-primary/15 text-primary px-1.5 py-0.5 rounded-md font-medium">{modeLabel}</span>
                <span className="text-[10px] bg-secondary text-muted-foreground px-1.5 py-0.5 rounded-md">{typeLabel}</span>
                <span className="text-[10px] bg-secondary text-muted-foreground px-1.5 py-0.5 rounded-md">Bo{tournament.bestOf * 2 - 1}</span>
              </div>
            </div>
            <TournamentSettingsDialog
              mode={tournament.mode}
              type={tournament.type}
              bestOf={tournament.bestOf}
              tournamentDate={tournament.tournamentDate}
              venueStreet={tournament.venueStreet}
              venueHouseNumber={tournament.venueHouseNumber}
              venuePostalCode={tournament.venuePostalCode}
              venueCity={tournament.venueCity}
              motto={tournament.motto}
              breakMinutes={tournament.breakMinutes}
              certificateText={tournament.certificateText}
              organizerName={tournament.organizerName}
              sponsors={tournament.sponsors}
              certificateBgUrl={tournament.certificateBgUrl}
              certificateFontFamily={tournament.certificateFontFamily}
              certificateFontSize={tournament.certificateFontSize}
              certificateTextColor={tournament.certificateTextColor}
              certificateExtraSizes={tournament.certificateExtraSizes}
              started={tournament.started}
              openingVideoUrl={tournament.openingVideoUrl || null}
              tournamentId={tournament.id}
              onUpdateMode={updateTournamentMode}
              onUpdateType={updateTournamentType}
              onUpdateBestOf={updateBestOf}
              onUpdateDetails={updateDetails}
            />
            {tournament.openingVideoUrl && (
              <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground" onClick={() => setOpeningVideoPlayerOpen(true)} title="Eröffnungsvideo abspielen">
                <Video className="h-4 w-4" />
              </Button>
            )}
          </div>
          <div className="flex items-center gap-2">
            {canStart && (
              <Button
                onClick={() => {
                  generateBracket();
                  setTab(isRoundRobin || isSwiss || isKaiser || isHandicap ? 'scoring' : 'bracket');
                }}
                className="h-9 font-semibold glow-green"
                size="sm"
              >
                <Play className="mr-1 h-4 w-4" />
                Start
              </Button>
            )}
            {tournament.started && (
              <div className="flex gap-2">
                {!tournament.matches.some(m => m.status !== 'pending' || (m.sets && m.sets.length > 0)) && (
                  <Button
                    variant="destructive"
                    size="sm"
                    onClick={() => {
                      if (window.confirm('Möchtest du das Turnier wirklich zurücksetzen? Die Auslosung geht dabei verloren.')) {
                        resetTournament();
                      }
                    }}
                    className="gap-1 opacity-90"
                  >
                    Zurücksetzen
                  </Button>
                )}
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setSelectedTournamentId(null)}
                  className="text-muted-foreground hover:text-foreground"
                >
                  <RotateCcw className="mr-1 h-4 w-4" />
                  Zurück
                </Button>
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Info bar */}
      <div className="container py-2.5">
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
          <span className="font-medium text-foreground/70">{tournament.players.length} Spieler</span>
          {isDoubles && <span className="font-medium text-foreground/70">{tournament.doublesPairs.length} Paare</span>}
          {isGroupKnockout && tournament.started && (
            <>
              <span className="text-border">·</span>
              <span className="text-primary font-semibold">{tournament.phase === 'knockout' ? 'K.O.-Runde' : 'Gruppenphase'}</span>
            </>
          )}
          {tournament.started && (
            <>
              <span className="text-border">·</span>
              <span>{tournament.matches.filter(m => m.status === 'completed').length}/{tournament.matches.length} Spiele</span>
            </>
          )}
          {tournament.tournamentDate && (
            <>
              <span className="text-border">·</span>
              <span>📅 {new Date(tournament.tournamentDate + 'T00:00:00').toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' })}</span>
            </>
          )}
          {(tournament.venueCity || tournament.venueStreet) && (
            <>
              <span className="text-border">·</span>
              <span>📍 {[tournament.venueStreet, tournament.venueHouseNumber, tournament.venuePostalCode, tournament.venueCity].filter(Boolean).join(' ')}</span>
            </>
          )}
          {tournament.motto && (
            <>
              <span className="text-border">·</span>
              <span className="italic text-foreground/50">„{tournament.motto}"</span>
            </>
          )}
        </div>
      </div>

      {/* Main content */}
      <div className="container pb-24">
        <Tabs value={tab} onValueChange={setTab} className="w-full">
          <TabsList className={`w-full bg-secondary/50 h-11 p-1 rounded-xl grid`} style={{ gridTemplateColumns: `repeat(${tabCount}, minmax(0, 1fr))` }}>
            <TabsTrigger value="players" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <Users className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Spieler</span>
            </TabsTrigger>
            {isDoubles && (
              <TabsTrigger value="doubles" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
                <Users2 className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">Doppel</span>
              </TabsTrigger>
            )}
            {isTeam && (
              <TabsTrigger value="teams" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
                <Shield className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">Teams</span>
              </TabsTrigger>
            )}
            <TabsTrigger value="clubs" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <Building2 className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Vereine</span>
            </TabsTrigger>
            <TabsTrigger value="bracket" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <Swords className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">{isRoundRobin || isSwiss || isHandicap ? 'Tabelle' : isKaiser ? 'Rangliste' : isGroupKnockout ? 'Gruppen' : 'Bracket'}</span>
            </TabsTrigger>
            <TabsTrigger value="scoring" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <PenLine className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Ergebnis</span>
            </TabsTrigger>
            <TabsTrigger value="overview" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <ClipboardList className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Übersicht</span>
            </TabsTrigger>
            <TabsTrigger value="media" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <Film className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Medien</span>
            </TabsTrigger>
            <TabsTrigger value="live" className="rounded-lg data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm font-medium text-xs gap-1 transition-all">
              <Monitor className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Live</span>
            </TabsTrigger>
          </TabsList>
          <div className="flex justify-end mt-2">
            {tab === 'live' && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => window.open(`/live/${selectedTournamentId}`, '_blank')}
                className="gap-1 text-xs"
              >
                <Monitor className="h-3 w-3" />
                Im neuen Fenster öffnen
              </Button>
            )}
            {tab === 'bracket' && isRoundRobin && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => window.open(`/standings/${selectedTournamentId}`, '_blank')}
                className="gap-1 text-xs"
              >
                <Monitor className="h-3 w-3" />
                Tabelle im neuen Fenster
              </Button>
            )}
          </div>

          <div className="mt-4">
            <TabsContent value="players">
              <div className="mb-3 flex flex-wrap gap-2">
                <PlayerImportExport
                  players={tournament.players}
                  onImport={importPlayers}
                  started={tournament.started}
                />
                {!tournament.started && (
                  <ImportFromClubPlayers
                    clubs={clubs}
                    clubPlayers={clubPlayers}
                    getPlayersForClub={getPlayersForClub}
                    onImportPlayers={(players) => {
                      const withConsent: string[] = [];
                      for (const p of players) {
                        addPlayer(p.name, p.club, p.ttr, p.gender, p.birthDate, p.postalCode, p.city, p.street, p.houseNumber, p.phone, p.voiceNameUrl || undefined, p.photoConsent);
                        if (p.photoConsent) withConsent.push(p.name);
                      }
                      if (withConsent.length > 0) {
                        toast.success(`Fotoerlaubnis für ${withConsent.length} Spieler übernommen`);
                      }
                    }}
                    existingPlayerNames={tournament.players.map(p => p.name)}
                  />
                )}
              </div>
              <PlayerManager
                players={tournament.players}
                onAdd={addPlayer}
                onRemove={removePlayer}
                onUpdate={updatePlayer}
                started={tournament.started}
                clubs={clubs}
                onAddClub={addClub}
                tournamentName={tournament.name}
                tournamentDate={tournament.tournamentDate}
                venueString={venueString}
                logoUrl={tournament.logoUrl}
                matches={tournament.matches}
                tournamentId={selectedTournamentId}
                bestOf={tournament.bestOf}
                 totalRounds={tournament.rounds}
                 getPlayer={getPlayer}
                 getParticipantName={getParticipantName}
                 mode={tournament.mode}
               />
            </TabsContent>

            {isDoubles && (
              <TabsContent value="doubles">
                <DoublesManager
                  players={tournament.players}
                  doublesPairs={tournament.doublesPairs}
                  onAddPair={addDoublesPair}
                  onRemovePair={removeDoublesPair}
                  onAutoGenerate={autoGenerateDoublesPairs}
                  started={tournament.started}
                  getPlayer={getPlayer}
                  tournamentId={tournament.id || undefined}
                />
              </TabsContent>
            )}

            {isTeam && (
              <TabsContent value="teams">
                <TeamManager
                  players={tournament.players}
                  teams={tournament.teams}
                  teamPlayers={tournament.teamPlayers}
                  teamMode={tournament.teamMode}
                  started={tournament.started}
                  onAddTeam={addTeam}
                  onRemoveTeam={removeTeam}
                  onAddPlayerToTeam={addPlayerToTeam}
                  onRemovePlayerFromTeam={removePlayerFromTeam}
                  getPlayer={getPlayer}
                />
              </TabsContent>
            )}

            <TabsContent value="clubs">
              <ClubManager
                clubs={clubs}
                players={tournament.players}
                onAdd={addClub}
                onRemove={removeClub}
                onUpdate={updateClub}
                onImportClubsWithPlayers={handleImportClubsWithPlayers}
              />
            </TabsContent>

            <TabsContent value="bracket">
              {isGroupKnockout ? (
                <>
                  {tournament.phase === 'group' || !tournament.phase ? (
                    <>
                      <div className="flex justify-end mb-2">
                        <Button
                          variant="outline"
                          size="sm"
                          className="gap-1 text-xs"
                          onClick={() => {
                            const groupMatches = tournament.matches.filter(m => m.groupNumber !== undefined && m.groupNumber !== null);
                            const gc = Math.max(...tournament.players.map(p => (p.groupNumber ?? 0)), 0) + 1;
                            generateGroupStageReport({
                              matches: groupMatches,
                              players: tournament.players,
                              getParticipantName: isDoubles ? getParticipantName : (id) => getPlayer(id)?.name || '—',
                              groupCount: gc,
                              tournamentName: tournament.name,
                              bestOf: tournament.bestOf,
                              logoUrl: tournament.logoUrl,
                              tournamentDate: tournament.tournamentDate,
                              venueString,
                              motto: tournament.motto,
                            });
                          }}
                        >
                          <FileDown className="h-3 w-3" />
                          Gruppenphase PDF
                        </Button>
                      </div>
                      <GroupStageView
                        matches={tournament.matches.filter(m => m.groupNumber !== undefined && m.groupNumber !== null)}
                        players={tournament.players}
                        getParticipantName={isDoubles ? getParticipantName : (id) => getPlayer(id)?.name || '—'}
                        onAdvanceToKnockout={advanceToKnockout}
                        groupCount={Math.max(...tournament.players.map(p => (p.groupNumber ?? 0)), 0) + 1}
                      />
                    </>
                  ) : (
                    <div className="space-y-6">
                      <GroupStageView
                        matches={tournament.matches.filter(m => m.groupNumber !== undefined && m.groupNumber !== null)}
                        players={tournament.players}
                        getParticipantName={isDoubles ? getParticipantName : (id) => getPlayer(id)?.name || '—'}
                        groupCount={Math.max(...tournament.players.map(p => (p.groupNumber ?? 0)), 0) + 1}
                      />
                      <h3 className="text-lg font-bold">🏆 K.O.-Runde</h3>
                      <TournamentBracket
                        matches={tournament.matches.filter(m => m.groupNumber === undefined || m.groupNumber === null)}
                        rounds={tournament.rounds}
                        getPlayer={isDoubles
                          ? (id) => id ? { id, name: getParticipantName(id), club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' } : null
                          : getPlayer
                        }
                      />
                    </div>
                  )}
                </>
              ) : isDoubleKnockout ? (
                <DoubleEliminationBracket
                  matches={tournament.matches}
                  wbRounds={tournament.rounds}
                  getPlayer={isDoubles
                    ? (id) => id ? { id, name: getParticipantName(id), club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' } : null
                    : getPlayer
                  }
                />
              ) : isSwiss ? (
                <SwissStandings
                  matches={tournament.matches}
                  players={isDoubles
                    ? tournament.doublesPairs.map(dp => ({ id: dp.player1Id, name: dp.pairName, club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' }))
                    : tournament.players
                  }
                  getParticipantName={isDoubles ? getParticipantName : (id) => getPlayer(id)?.name || '—'}
                  onGenerateNextRound={generateNextSwissRound}
                  currentRound={tournament.rounds}
                  isDoubles={isDoubles}
                />
              ) : isRoundRobin || isHandicap ? (
                <RoundRobinStandings
                  matches={tournament.matches}
                  getParticipantName={isDoubles ? getParticipantName : (id) => getPlayer(id)?.name || '—'}
                  isDoubles={isDoubles}
                />
              ) : isKaiser ? (
                <div className="text-center text-muted-foreground py-8">
                  <p>Die Kaiser-Rangliste findest du im Tab „Ergebnis".</p>
                </div>
              ) : (
                <TournamentBracket
                  matches={tournament.matches}
                  rounds={tournament.rounds}
                  getPlayer={isDoubles
                    ? (id) => id ? { id, name: getParticipantName(id), club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' } : null
                    : getPlayer
                  }
                />
              )}
            </TabsContent>

            <TabsContent value="scoring">
              {isKaiser ? (
                <KaiserScoring
                  matches={tournament.matches}
                  players={tournament.players}
                  getPlayer={getPlayer}
                  getParticipantName={getParticipantName}
                  onUpdateScore={updateMatchScore}
                  onSetActive={setMatchActive}
                  onGenerateNextRound={generateNextKaiserRound}
                  kaiserDurationMinutes={tournament.kaiserDurationMinutes}
                  onUpdateDuration={updateKaiserDuration}
                  currentRound={tournament.rounds}
                  bestOf={tournament.bestOf}
                  tableCount={tournament.tableCount}
                  onTableCountChange={setTableCount}
                  started={tournament.started}
                />
              ) : isTeam && tournament.teamMode ? (
                <TeamEncounterScoring
                  matches={tournament.matches}
                  teams={tournament.teams}
                  teamPlayers={tournament.teamPlayers}
                  teamMode={tournament.teamMode}
                  bestOf={tournament.bestOf}
                  earlyFinishEnabled={tournament.earlyFinishEnabled}
                  getPlayer={getPlayer}
                  encounterGames={encounterGames}
                  loadEncounterGames={loadEncounterGames}
                  updateEncounterGameScore={updateEncounterGameScore}
                  onSetActive={setMatchActive}
                  tableCount={tournament.tableCount}
                  onTableCountChange={setTableCount}
                  onAutoAssign={autoAssignTables}
                />
              ) : (
                <MatchScoring
                  matches={tournament.matches}
                  getPlayer={isDoubles
                    ? (id) => id ? { id, name: getParticipantName(id), club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' } : null
                    : getPlayer
                  }
                  onUpdateScore={updateMatchScore}
                  onSetActive={setMatchActive}
                  tableCount={tournament.tableCount}
                  onTableCountChange={setTableCount}
                  onAutoAssign={autoAssignTables}
                  bestOf={tournament.bestOf}
                  getParticipantName={getParticipantName}
                  tournamentName={tournament.name}
                  rounds={tournament.rounds}
                  tournamentId={selectedTournamentId}
                  logoUrl={tournament.logoUrl}
                  tournamentDate={tournament.tournamentDate}
                  venueString={venueString}
                   motto={tournament.motto}
                   sponsors={tournament.sponsors}
                   isHandicap={isHandicap}
                   players={tournament.players}
                   doublesPairs={tournament.doublesPairs}
                   mode={tournament.mode}
                   breakMinutes={tournament.breakMinutes}
                 />
              )}
            </TabsContent>

            <TabsContent value="overview">
              <TournamentOverview
                tournamentName={tournament.name}
                matches={tournament.matches}
                rounds={tournament.rounds}
                logoUrl={tournament.logoUrl}
                bestOf={tournament.bestOf}
                tournamentId={selectedTournamentId}
                getPlayer={isDoubles
                  ? (id) => id ? { id, name: getParticipantName(id), club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' } : null
                  : getPlayer
                }
                getParticipantName={getParticipantName}
                players={isDoubles
                  ? tournament.doublesPairs.map(dp => ({ id: dp.player1Id, name: dp.pairName, club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' }))
                  : tournament.players
                }
                 tournamentDate={tournament.tournamentDate}
                 venueString={venueString}
                 motto={tournament.motto}
                 mode={tournament.mode}
                 organizerName={tournament.organizerName}
                 sponsors={tournament.sponsors}
                 certificateBgUrl={tournament.certificateBgUrl}
                 certificateText={tournament.certificateText}
                 certificateFontFamily={tournament.certificateFontFamily}
                 certificateFontSize={tournament.certificateFontSize}
                 certificateTextColor={tournament.certificateTextColor}
                 certificateLineSizes={tournament.certificateLineSizes}
                 certificateExtraSizes={tournament.certificateExtraSizes}
                 certificateHiddenFields={tournament.certificateHiddenFields}
                 onSaveCertificateSettings={(settings) => {
                   const parts = settings.venueString.split(',').map(s => s.trim());
                   updateDetails({
                     certificate_text: settings.certificateText,
                     certificate_line_sizes: settings.certificateLineSizes,
                     certificate_extra_sizes: settings.certificateExtraSizes,
                     certificate_hidden_fields: settings.certificateHiddenFields,
                     motto: settings.motto,
                     venue_street: parts[0] || '',
                     venue_city: parts.slice(1).join(', ') || '',
                      organizer_name: settings.organizerName,
                    } as any);
                 }}
                />
            </TabsContent>

            <TabsContent value="media">
              <TournamentMediaTab
                tournamentId={selectedTournamentId!}
                tournamentName={tournament.name}
                matches={tournament.matches}
                getParticipantName={getParticipantName}
                started={tournament.started}
                logoUrl={tournament.logoUrl}
              />
            </TabsContent>

            <TabsContent value="live">
              <LiveDashboard
                matches={tournament.matches}
                rounds={tournament.rounds}
                getPlayer={isDoubles
                  ? (id) => id ? { id, name: getParticipantName(id), club: '', gender: '', birthDate: null, ttr: 0, postalCode: '', city: '', street: '', houseNumber: '', phone: '' } : null
                  : getPlayer
                }
                getParticipantName={getParticipantName}
                mode={tournament.mode}
                phase={tournament.phase}
                players={tournament.players}
                groupCount={Math.max(...tournament.players.map(p => (p.groupNumber ?? -1) + 1), 0)}
              />
            </TabsContent>
          </div>
        </Tabs>
      </div>

      <Dialog open={openingVideoPlayerOpen} onOpenChange={setOpeningVideoPlayerOpen}>
        <DialogContent className="max-w-[95vw] max-h-[95vh] p-0 bg-black/95 border-none overflow-hidden flex items-center justify-center">
          {openingVideoPlayerOpen && tournament.openingVideoUrl && (
            <video
              src={tournament.openingVideoUrl}
              controls
              autoPlay
              className="max-w-full max-h-[90vh] rounded"
            />
          )}
        </DialogContent>
      </Dialog>
    </PageTransition>
  );
};

export default Index;
